"""empty message

Revision ID: 548ab630f7ed
Revises: 
Create Date: 2022-03-13 11:10:45.786723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '548ab630f7ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grades',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('cohort', sa.String(length=128), nullable=False),
    sa.Column('ip_scores', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cohort')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grades')
    # ### end Alembic commands ###
