"""empty message

Revision ID: 6293f8cd9913
Revises: 653f815bb774
Create Date: 2022-03-13 15:19:56.151013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6293f8cd9913'
down_revision = '653f815bb774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('email', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grades', 'email')
    # ### end Alembic commands ###
