"""empty message

Revision ID: 653f815bb774
Revises: 548ab630f7ed
Create Date: 2022-03-13 12:01:03.816312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '653f815bb774'
down_revision = '548ab630f7ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('grades_cohort_key', 'grades', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('grades_cohort_key', 'grades', ['cohort'])
    # ### end Alembic commands ###
